version: '3'

services:
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    env_file: .env.oauth
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
