---
version: '3.7'

services:
  traefik:
    image: traefik:v2.6.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_network
    ports:
      - "9101:9101" #metrics
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./configs:/configs:ro
      - /opt/traefik/data/traefik/letsencrypt:/letsencrypt/
    labels:
      - "traefik.docker.network=traefik_network"
      - "traefik.enable=true"
      - 'traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASICAUTH}'
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth, security-headers@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  traefik_network:
    external: true
